CCommonPromptMediator = require "logic/commonPrompt/CCommonPromptMediator"
CCommonPromptProxy = require "logic/commonPrompt/CCommonPromptProxy"
CCommonPromptResponseResultDisplayCommand = require "logic/commonPrompt/CCommonPromptResponseResultDisplayCommand"
CCommonPromptPopupDisplayCommand = require "logic/commonPrompt/CCommonPromptPopupDisplayCommand"