CToCheckVersionEvent = require "logic/gameState/event/CToCheckVersionEvent"
CToBatchUpdateEvent = require "logic/gameState/event/CToBatchUpdateEvent"
CToServerAuthEvent = require "logic/gameState/event/CToServerAuthEvent"
CToLoginEvent = require "logic/gameState/event/CToLoginEvent"
CToPVPMatchEvent = require "logic/gameState/event/CToPVPMatchEvent"
CToMainCampsiteEvent = require "logic/gameState/event/CToMainCampsiteEvent"
CToMallEvent = require "logic/gameState/event/CToMallEvent"
