CMainCampsiteMediator = require "logic/mainCampsite/CMainCampsiteMediator"
CMainCampsiteProxy = require "logic/mainCampsite/CMainCampsiteProxy"
CMainCampsiteRequestPackDataCommand = require "logic/mainCampsite/CMainCampsiteRequestPackDataCommand"
CMainCampsiteRequestRecruitmentOfficeDataCommand = require "logic/mainCampsite/CMainCampsiteRequestRecruitmentOfficeDataCommand"
CMainCampsiteRequestRoleListDataCommand = require "logic/mainCampsite/CMainCampsiteRequestRoleListDataCommand"

CMainCampsiteRequestAddDataCommand = require "logic/mainCampsite/CMainCampsiteRequestAddDataCommand"
