local Des_lang_table = {}
if GlobalDataConfig.lang == "cnt" then
    local _lang = require ("configs/uitext/UIText_Des_cnt")
    setmetatable(Des_lang_table, _lang)
end


if GlobalDataConfig.lang == "en" then
    local _lang = require ("configs/uitext/UIText_Des_en")
    setmetatable(Des_lang_table, _lang)
end


if GlobalDataConfig.lang == "cn" then
    local _lang = require ("configs/uitext/UIText_Des_cn")
    setmetatable(Des_lang_table, _lang)
end

---@class UITextInfo
---@field Des string
local __default_values = 
{
		
}

local data = 
{

	["RECRUITMENT_EXIT_BUILDING_BUTTON"] =
	{
		Des = Des_lang_table["RECRUITMENT_EXIT_BUILDING_BUTTON"],
	},
	["RECRUITMENT_FLASH_BUTTON"] =
	{
		Des = Des_lang_table["RECRUITMENT_FLASH_BUTTON"],
	},
	["RECRUITMENT_PRESS_BUTTON"] =
	{
		Des = Des_lang_table["RECRUITMENT_PRESS_BUTTON"],
	},
	["RECRUITMENT_HIRE_BUTTOM"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_BUTTOM"],
	},
	["RECRUITMENT_FLASH_TIME"] =
	{
		Des = Des_lang_table["RECRUITMENT_FLASH_TIME"],
	},
	["RECRUITMENT_FLASH_BUY"] =
	{
		Des = Des_lang_table["RECRUITMENT_FLASH_BUY"],
	},
	["RECRUITMENT_HIRE_RESOURCE_NOT_ENOUGH"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_RESOURCE_NOT_ENOUGH"],
	},
	["RECRUITMENT_HIRE_CHARACTER_FREE"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_CHARACTER_FREE"],
	},
	["RECRUITMENT_HIRE_SELL_OUT"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_SELL_OUT"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_LABEL"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_LABEL"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_1"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_1"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_LOCK"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_LOCK"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_LOCK_TIPS"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_LOCK_TIPS"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_1_NONE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_1_NONE"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_1_ORC"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_1_ORC"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_1_HUMAN"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_1_HUMAN"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_1_ELF"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_1_ELF"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2_NONE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2_NONE"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2_WALK"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2_WALK"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2_RIDING"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2_RIDING"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2_FLYING"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2_FLYING"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_2_HEAVY"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_2_HEAVY"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_NONE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_NONE"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_SWORD"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_SWORD"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_AXE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_AXE"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_LANCE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_LANCE"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_BOW"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_BOW"],
	},
	["RECRUITMENT_CHARACTER_TENDENCY_3_CANE"] =
	{
		Des = Des_lang_table["RECRUITMENT_CHARACTER_TENDENCY_3_CANE"],
	},
	["RECRUITMENT_HIRE_SUCCESS_PLAY_BREAK"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_SUCCESS_PLAY_BREAK"],
	},
	["RECRUITMENT_HIRE_SUCCESS_TITLE"] =
	{
		Des = Des_lang_table["RECRUITMENT_HIRE_SUCCESS_TITLE"],
	},
	["CHARACTER_BASIC_PHYIE_ORC"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_ORC"],
	},
	["CHARACTER_BASIC_PHYIE_HUMAN"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_HUMAN"],
	},
	["CHARACTER_BASIC_PHYIE_ELF"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_ELF"],
	},
	["CHARACTER_BASIC_PHYIE_DWARF"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_DWARF"],
	},
	["CHARACTER_BASIC_PHYIE_UNDEAD"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_UNDEAD"],
	},
	["CHARACTER_BASIC_PHYIE_ORC_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_ORC_INFO"],
	},
	["CHARACTER_BASIC_PHYIE_HUMAN_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_HUMAN_INFO"],
	},
	["CHARACTER_BASIC_PHYIE_ELF_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_ELF_INFO"],
	},
	["CHARACTER_BASIC_PHYIE_DWARF_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_DWARF_INFO"],
	},
	["CHARACTER_BASIC_PHYIE_UNDEAD_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_PHYIE_UNDEAD_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SOLDIER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SOLDIER"],
	},
	["CHARACTER_BASIC_CLASS_MERCENARY"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_MERCENARY"],
	},
	["CHARACTER_BASIC_CLASS_SWORDMASTER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SWORDMASTER"],
	},
	["CHARACTER_BASIC_CLASS_GUARD"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_GUARD"],
	},
	["CHARACTER_BASIC_CLASS_ROYALGUARD"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ROYALGUARD"],
	},
	["CHARACTER_BASIC_CLASS_CAVALRY"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_CAVALRY"],
	},
	["CHARACTER_BASIC_CLASS_SCOUT"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SCOUT"],
	},
	["CHARACTER_BASIC_CLASS_FREELANCER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_FREELANCER"],
	},
	["CHARACTER_BASIC_CLASS_KNIGHT"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_KNIGHT"],
	},
	["CHARACTER_BASIC_CLASS_CONQUEROR"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_CONQUEROR"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER"],
	},
	["CHARACTER_BASIC_CLASS_ARBALEST"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARBALEST"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE"],
	},
	["CHARACTER_BASIC_CLASS_RONIN"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_RONIN"],
	},
	["CHARACTER_BASIC_CLASS_RANGER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_RANGER"],
	},
	["CHARACTER_BASIC_CLASS_PRIEST"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_PRIEST"],
	},
	["CHARACTER_BASIC_CLASS_HOLYHEALER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HOLYHEALER"],
	},
	["CHARACTER_BASIC_CLASS_BISHOP"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BISHOP"],
	},
	["CHARACTER_BASIC_CLASS_WARLOCK"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WARLOCK"],
	},
	["CHARACTER_BASIC_CLASS_SOURCES"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SOURCES"],
	},
	["CHARACTER_BASIC_CLASS_WIZARD"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WIZARD"],
	},
	["CHARACTER_BASIC_CLASS_HOLYPRIEST"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HOLYPRIEST"],
	},
	["CHARACTER_BASIC_CLASS_SAGE"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SAGE"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER"],
	},
	["CHARACTER_BASIC_CLASS_SHOOTER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SHOOTER"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONTAMER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONTAMER"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONKNIGHT"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONKNIGHT"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONSLAYER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONSLAYER"],
	},
	["CHARACTER_BASIC_CLASS_WARRIOR"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WARRIOR"],
	},
	["CHARACTER_BASIC_CLASS_BERSERKER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BERSERKER"],
	},
	["CHARACTER_BASIC_CLASS_MADORC"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_MADORC"],
	},
	["CHARACTER_BASIC_CLASS_URUKHAI"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_URUKHAI"],
	},
	["CHARACTER_BASIC_CLASS_IRONORC"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_IRONORC"],
	},
	["CHARACTER_BASIC_CLASS_WOLFRAIDER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WOLFRAIDER"],
	},
	["CHARACTER_BASIC_CLASS_LIGHTWOLF"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_LIGHTWOLF"],
	},
	["CHARACTER_BASIC_CLASS_HURRICANE"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HURRICANE"],
	},
	["CHARACTER_BASIC_CLASS_PIONEER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_PIONEER"],
	},
	["CHARACTER_BASIC_CLASS_BASTION"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BASTION"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER"],
	},
	["CHARACTER_BASIC_CLASS_HUNTER"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HUNTER"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE"],
	},
	["CHARACTER_BASIC_CLASS_SOLDIER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SOLDIER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_MERCENARY_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_MERCENARY_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SWORDMASTER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SWORDMASTER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_GUARD_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_GUARD_INFO"],
	},
	["CHARACTER_BASIC_CLASS_ROYALGUARD_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ROYALGUARD_INFO"],
	},
	["CHARACTER_BASIC_CLASS_CAVALRY_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_CAVALRY_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SCOUT_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SCOUT_INFO"],
	},
	["CHARACTER_BASIC_CLASS_FREELANCER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_FREELANCER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_KNIGHT_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_KNIGHT_INFO"],
	},
	["CHARACTER_BASIC_CLASS_CONQUEROR_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_CONQUEROR_INFO"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_ARBALEST_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARBALEST_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"],
	},
	["CHARACTER_BASIC_CLASS_RONIN_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_RONIN_INFO"],
	},
	["CHARACTER_BASIC_CLASS_RANGER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_RANGER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_PRIEST_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_PRIEST_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HOLYHEALER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HOLYHEALER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_BISHOP_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BISHOP_INFO"],
	},
	["CHARACTER_BASIC_CLASS_WARLOCK_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WARLOCK_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SOURCES_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SOURCES_INFO"],
	},
	["CHARACTER_BASIC_CLASS_WIZARD_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WIZARD_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HOLYPRIEST_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HOLYPRIEST_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SAGE_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SAGE_INFO"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_SHOOTER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_SHOOTER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONTAMER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONTAMER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONKNIGHT_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONKNIGHT_INFO"],
	},
	["CHARACTER_BASIC_CLASS_DRAGONSLAYER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_DRAGONSLAYER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_WARRIOR_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WARRIOR_INFO"],
	},
	["CHARACTER_BASIC_CLASS_BERSERKER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BERSERKER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_MADORC_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_MADORC_INFO"],
	},
	["CHARACTER_BASIC_CLASS_URUKHAI_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_URUKHAI_INFO"],
	},
	["CHARACTER_BASIC_CLASS_IRONORC_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_IRONORC_INFO"],
	},
	["CHARACTER_BASIC_CLASS_WOLFRAIDER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_WOLFRAIDER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_LIGHTWOLF_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_LIGHTWOLF_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HURRICANE_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HURRICANE_INFO"],
	},
	["CHARACTER_BASIC_CLASS_PIONEER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_PIONEER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_BASTION_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_BASTION_INFO"],
	},
	["CHARACTER_BASIC_CLASS_ARCHER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_ARCHER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HUNTER_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HUNTER_INFO"],
	},
	["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"] =
	{
		Des = Des_lang_table["CHARACTER_BASIC_CLASS_HAWKEYE_INFO"],
	},
}

do
    local base = {
        __index = __default_values,
        __newindex = function()
            error( "Attempt to modify read-only table" )
        end
    }
    for k, v in pairs(data) do
        setmetatable(v, base)
    end
    base.__metatable = false
end

return data
